PHRASES = [
    "The only way to do great work is to love what you do.",
    "The best way to predict the future is to create it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The harder you work, the luckier you get.",
    "Believe you can and you're halfway there.",
    "Don't let yesterday take up too much of today.",
    "The only thing constant is change. Embrace it.",
    "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
    "The best revenge is massive success.",
    "It's not about being the best, it's about being better than you were yesterday.",
    "The road to success is paved with setbacks.",
    "Small steps, big achievements.",
    "Focus on your strengths and improve your weaknesses.",
    "Your time is limited, don't waste it living someone else's life.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "The journey of a thousand miles begins with a single step."
]